Repository typelevel/cats-effect, pull requests merged in 2018-03, with the labels that each got.

#142 Fix/replace incorrent "racePair derives race" law
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala
Labels: bug

#144 Re-add Kleisli instances for Sync, Async and Concurrent
  core/shared/src/main/scala/cats/effect/Async.scala
  core/shared/src/main/scala/cats/effect/Concurrent.scala
  core/shared/src/main/scala/cats/effect/Sync.scala
  laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Labels: enhancement

#161 Update to cats 1.1.0
  build.sbt
Labels: chore

#171 Remove AndThen, as StateT was fixed in Cats 1.1
  core/shared/src/main/scala/cats/effect/Sync.scala
  core/shared/src/main/scala/cats/effect/internals/AndThen.scala
  core/shared/src/test/scala/cats/effect/internals/AndThenTests.scala
Labels: chore
