Repository typelevel/cats-effect, pull requests merged in 2018-05, with the labels that each got.

#228 Fix onCancelRaiseError, plus add law
  build.sbt
  core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala
  core/shared/src/main/scala/cats/effect/internals/IOCancel.scala
  core/shared/src/main/scala/cats/effect/internals/IOConnection.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
  site/src/main/tut/datatypes/io.md
Labels: bug

#241 Move uncancelable down to Bracket. Add laws specifying interaction.
  build.sbt
  core/shared/src/main/scala/cats/effect/Bracket.scala
  core/shared/src/main/scala/cats/effect/Concurrent.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Sync.scala
  core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
  laws/shared/src/main/scala/cats/effect/laws/BracketLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/BracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentEffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala
  laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Labels: breaking change, enhancement

#237 Restate ConcurrentLaws to support auto-cancelable run loops
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
Labels: breaking change

#248 Fix #123: introduce Async.asyncF
  build.sbt
  core/shared/src/main/scala/cats/effect/Async.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/implicits/package.scala
  core/shared/src/main/scala/cats/effect/internals/Callback.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
  laws/shared/src/test/scala/cats/effect/LTask.scala
Labels: breaking change, enhancement

#250 Optimize async trampoline, add ContextSwitch
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/AsyncBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/HandleErrorBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/ShallowBindBenchmark.scala
  build.sbt
  core/js/src/main/scala/cats/effect/internals/IOPlatform.scala
  core/js/src/main/scala/cats/effect/internals/IOTimer.scala
  core/js/src/main/scala/cats/effect/internals/TrampolineEC.scala
  core/jvm/src/main/scala/cats/effect/internals/IOTimer.scala
  core/jvm/src/main/scala/cats/effect/internals/TrampolineEC.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/internals/ArrayStack.scala
  core/shared/src/main/scala/cats/effect/internals/Callback.scala
  core/shared/src/main/scala/cats/effect/internals/IOCancel.scala
  core/shared/src/main/scala/cats/effect/internals/IOConnection.scala
  core/shared/src/main/scala/cats/effect/internals/IOForkedStart.scala
  core/shared/src/main/scala/cats/effect/internals/IOParMap.scala
  core/shared/src/main/scala/cats/effect/internals/IORace.scala
  core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala
  core/shared/src/main/scala/cats/effect/internals/IOShift.scala
  core/shared/src/main/scala/cats/effect/internals/IOStart.scala
  core/shared/src/main/scala/cats/effect/internals/Trampoline.scala
  core/shared/src/main/scala/cats/effect/internals/package.scala
  core/shared/src/test/scala/cats/effect/internals/ArrayStackTests.scala
  core/shared/src/test/scala/cats/effect/internals/CallbackTests.scala
  laws/shared/src/main/scala/cats/effect/laws/util/TestContext.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
Labels: chore

#255 Use Throwable#addSupressed when IO.bracket fails in both use and release
  core/js/src/main/scala/cats/effect/internals/IOPlatform.scala
  core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala
  core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
  laws/js/src/test/scala/cats/effect/IOJSTests.scala
  laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala
Labels: enhancement
