Repository typelevel/cats-effect, pull requests merged in 2018-08, with the labels that each got.

#290 Concurrent, version 2
  build.sbt
  core/js/src/main/scala/cats/effect/internals/IOPlatform.scala
  core/shared/src/main/scala/cats/effect/Concurrent.scala
  core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala
  core/shared/src/main/scala/cats/effect/Fiber.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/concurrent/Deferred.scala
  core/shared/src/main/scala/cats/effect/internals/Callback.scala
  core/shared/src/main/scala/cats/effect/internals/MVarConcurrent.scala
  core/shared/src/main/scala/cats/effect/package.scala
  core/shared/src/test/scala/cats/effect/SyntaxTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentEffectLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/test/scala/cats/effect/IOCancelableTests.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
  laws/shared/src/test/scala/cats/effect/InstancesTests.scala
  laws/shared/src/test/scala/cats/effect/TestContextTests.scala
  site/src/main/tut/datatypes/io.md
  site/src/main/tut/typeclasses/concurrent-effect.md
  site/src/main/tut/typeclasses/concurrent.md
Labels: breaking change, enhancement

#303 Redundant Parallel in `Deferred` docs
  site/src/main/tut/concurrency/deferred.md
Labels: chore

#302 Docs for SyncIO
  site/src/main/resources/microsite/data/menu.yml
  site/src/main/tut/datatypes/index.md
  site/src/main/tut/datatypes/syncio.md
Labels: chore

#304 Added Related projects section
  README.md
Labels: chore

#296 Make Sync extend Defer
  build.sbt
  core/shared/src/main/scala/cats/effect/Sync.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
Labels: breaking change

#307 Modify @implicitNotFound messages for Clock, ContextShift, Timer
  core/shared/src/main/scala/cats/effect/Clock.scala
  core/shared/src/main/scala/cats/effect/ContextShift.scala
  core/shared/src/main/scala/cats/effect/Timer.scala
Labels: chore

#287 Add Concurrency Basics section
  site/src/main/tut/concurrency/basics.md
  site/src/main/tut/concurrency/index.md
Labels: chore

#317 Fix #316: fix IO.bracket to be stack safe; add laws to SyncLaws
  core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala
Labels: bug

#323 Remove compareAndSet and lazySet
  core/shared/src/main/scala/cats/effect/concurrent/Ref.scala
Labels: breaking change
