Repository typelevel/cats-effect, pull requests merged in 2018-04, with the labels that each got.

#177 Remove Sync instance for EitherT[Eval, Throwable, ?]
  core/shared/src/main/scala/cats/effect/Sync.scala
  laws/shared/src/test/scala/cats/effect/InstancesTests.scala
Labels: breaking change

#113 Add Bracket type class
  build.sbt
  core/shared/src/main/scala/cats/effect/Bracket.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Sync.scala
  core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
  laws/shared/src/main/scala/cats/effect/laws/BracketLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/BracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/ConcurrentTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/SyncTests.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
  laws/shared/src/test/scala/cats/effect/LTask.scala
  site/src/main/tut/datatypes/io.md
  site/src/main/tut/typeclasses/bracket.md
Labels: breaking change, enhancement

#183 Fix AsyncLaws.neverIsDerivedFromAsync, add param for disabling it
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/Parameters.scala
Labels: enhancement
