Repository typelevel/cats-effect, pull requests merged in 2020-09, with the labels that each got.

#1134 All things work stealing
  benchmarks/src/main/scala/cats/effect/benchmarks/AsyncBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/AttemptBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/DeepBindBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/HandleErrorBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/MapCallsBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/MapStreamBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/RedeemBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/RedeemWithBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/ShallowBindBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/WorkStealingBenchmark.scala
  core/js/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/java/cats/effect/WorkStealingQueueConstants.java
  core/jvm/src/main/java/cats/effect/WorkStealingThreadPoolConstants.java
  core/jvm/src/main/scala/cats/effect/IOFiberPlatform.scala
  core/jvm/src/main/scala/cats/effect/IOPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/ExternalQueue.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingQueue.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/jvm/src/test/scala/cats/effect/RunnersPlatform.scala
  core/jvm/src/test/scala/cats/effect/concurrent/DeferredJVMSpec.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
Labels: CE 3

#1164 Push per thread state to each thread and remove one source of contention
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
Labels: CE 3

#1156 Hierarchy renaming
  .github/workflows/ci.yml
  build.sbt
  concurrent/shared/src/main/scala/cats/effect/concurrent/MVar.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
  concurrent/shared/src/test/scala/cats/effect/concurrent/SyntaxSpec.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Resource.scala
  core/shared/src/main/scala/cats/effect/instances/AllInstances.scala
  core/shared/src/main/scala/cats/effect/instances/package.scala
  core/shared/src/main/scala/cats/effect/package.scala
  core/shared/src/main/scala/cats/effect/syntax/AllSyntax.scala
  core/shared/src/main/scala/cats/effect/syntax/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Allocate.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Concurrent.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Ref.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Spawn.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Temporal.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/AllInstances.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/SpawnInstances.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/AllSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/SpawnSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/package.scala
  kernel/shared/src/test/scala/cats/effect/kernel/SyntaxSpec.scala
  laws/shared/src/main/scala/cats/effect/laws/SpawnLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/SpawnTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalTests.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/PureConcGenerators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3

#1183 Refactor Resource interpreters to use (mostly) static typing
  core/shared/src/main/scala/cats/effect/Resource.scala
Labels: CE 3

#1186 Updated to build on ScalaJS for Dotty 0.27.0-RC1
  .github/workflows/ci.yml
  build.sbt
  core/js/src/main/scala-2/cats/effect/unsafe/PolyfillExecutionContext.scala
  core/js/src/main/scala-3/cats/effect/unsafe/PolyfillExecutionContext.scala
  kernel/js/src/main/scala/cats/effect/kernel/AsyncPlatform.scala
  project/plugins.sbt
Labels: CE 3

#1192 Gen hierarchy renaming
  concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
  concurrent/shared/src/test/scala/cats/effect/concurrent/SyntaxSpec.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Resource.scala
  core/shared/src/main/scala/cats/effect/instances/AllInstances.scala
  core/shared/src/main/scala/cats/effect/instances/package.scala
  core/shared/src/main/scala/cats/effect/package.scala
  core/shared/src/main/scala/cats/effect/syntax/AllSyntax.scala
  core/shared/src/main/scala/cats/effect/syntax/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Concurrent.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Ref.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/AllInstances.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/AllSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/GenSpawnSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/GenTemporalSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/package.scala
  kernel/shared/src/test/scala/cats/effect/kernel/SyntaxSpec.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/GenSpawnLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/GenSpawnTests.scala
  laws/shared/src/main/scala/cats/effect/laws/GenTemporalLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/GenTemporalTests.scala
  laws/shared/src/test/scala/cats/effect/EitherTPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/GenTemporalSpec.scala
  laws/shared/src/test/scala/cats/effect/IorTPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/KleisliPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/OptionTPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/TimeTSpec.scala
  laws/shared/src/test/scala/cats/effect/WriterTPureConcSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/PureConcGenerators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3

#1194 Disallow null in IO pure, delay and defer
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: CE 3

#1196 Remove unsound pattern matches from Resource
  core/shared/src/main/scala/cats/effect/Resource.scala
Labels: CE 3

#1202 Remove references to executed fibers
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingQueue.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
Labels: CE 3

#1203 Prevent accidental resuming of a done fiber
  core/js/src/main/scala/cats/effect/IOFiberConstants.scala
  core/jvm/src/main/java/cats/effect/IOFiberConstants.java
  core/shared/src/main/scala/cats/effect/IOFiber.scala
Labels: CE 3

#1199 Move Resource to kernel
  core/shared/src/main/scala/cats/effect/LiftIO.scala
  core/shared/src/main/scala/cats/effect/package.scala
  core/shared/src/test/scala/cats/effect/ResourceSpec.scala
  kernel/js/src/main/scala/cats/effect/kernel/ResourcePlatform.scala
  kernel/jvm/src/main/scala/cats/effect/kernel/ResourcePlatform.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
Labels: CE 3

#1211 Remove unsafe cast from Resource#invariant
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
Labels: CE 3

#1213 Make UnsafeRun[IO] available anywhere there is an IORuntime
  core/shared/src/main/scala/cats/effect/IO.scala
Labels: CE 3

#1224 Add Spawn#background and IO#background
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
Labels: CE 3

#1222 Purge cats implicits import from the codebase
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/AsyncBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/AttemptBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/DeepBindBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/ECBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/HandleErrorBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapCallsBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/MapStreamBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/ShallowBindBenchmark.scala
  core/jvm/src/main/scala/cats/effect/internals/ResourcePlatform.scala
  core/shared/src/main/scala/cats/effect/Concurrent.scala
  core/shared/src/main/scala/cats/effect/IOApp.scala
  site/src/main/mdoc/concurrency/deferred.md
  site/src/main/mdoc/concurrency/ref.md
  site/src/main/mdoc/concurrency/semaphore.md
  site/src/main/mdoc/datatypes/clock.md
  site/src/main/mdoc/datatypes/contextshift.md
  site/src/main/mdoc/datatypes/io.md
  site/src/main/mdoc/tracing/index.md
  site/src/main/mdoc/tutorial/tutorial.md
  site/src/main/mdoc/typeclasses/liftio.md
Labels: docs

#1223 Purge cats implicits import from the codebase
  benchmarks/src/main/scala/cats/effect/benchmarks/AsyncBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/WorkStealingBenchmark.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/MVar.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
  core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
  core/jvm/src/test/scala/cats/effect/concurrent/DeferredJVMSpec.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  core/shared/src/test/scala/cats/effect/SyncIOSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/DeferredSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/LensRefSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/MVarSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/RefSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/SemaphoreSpec.scala
  example/js/src/main/scala/cats/effect/example/Example.scala
  kernel/jvm/src/main/scala/cats/effect/kernel/ResourcePlatform.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ClockLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/GenTemporalLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/IsEq.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/Tolerance.scala
  laws/shared/src/test/scala/cats/effect/BaseSpec.scala
  laws/shared/src/test/scala/cats/effect/ClockSpec.scala
  laws/shared/src/test/scala/cats/effect/EitherTFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/EitherTPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/FreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/GenTemporalSpec.scala
  laws/shared/src/test/scala/cats/effect/IorTFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/IorTPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/KleisliFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/KleisliPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/OptionTFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/OptionTPureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/OutcomeSpec.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
  laws/shared/src/test/scala/cats/effect/ReaderWriterStateTFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/StateTFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/WriterTFreeSyncSpec.scala
  laws/shared/src/test/scala/cats/effect/WriterTPureConcSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/freeEval.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3

#1221 Refactor Semaphore for readability
  concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
Labels: CE 3

#1212 Getting started on docs
  .github/workflows/ci.yml
  build.sbt
  core/shared/src/main/scala/cats/effect/syntax/AllSyntax.scala
  core/shared/src/main/scala/cats/effect/syntax/package.scala
  docs/typeclasses.md
  hierarchy.svg
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/AllSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/GenSpawnSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/MonadCancelSyntax.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/package.scala
  kernel/shared/src/test/scala/cats/effect/kernel/SyntaxSpec.scala
  project/plugins.sbt
Labels: CE 3

#1234 Implement embed directly in Outcome
  benchmarks/src/main/scala/cats/effect/benchmarks/AsyncBenchmark.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
Labels: CE 3

#1241 Remove MVar
  concurrent/shared/src/main/scala/cats/effect/concurrent/MVar.scala
  concurrent/shared/src/test/scala/cats/effect/concurrent/SyntaxSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/MVarSpec.scala
Labels: CE 3

#1216 Add documentation page on testing with cats-effect
  README.md
  site/src/main/mdoc/testing/index.md
  site/src/main/resources/microsite/data/menu.yml
Labels: docs

#1239 MonadCancel scaladoc
  kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
  laws/shared/src/main/scala/cats/effect/laws/MonadCancelLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/MonadCancelTests.scala
Labels: CE 3, docs
