Repository typelevel/cats-effect, pull requests merged in 2020-07, with the labels that each got.

#914 Transformer instances for clock
  .gitignore
  build.sbt
  kernel/shared/src/main/scala/cats/effect/kernel/Clock.scala
  laws/shared/src/test/scala/cats/effect/BracketSpec.scala
  laws/shared/src/test/scala/cats/effect/ClockSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3

#847 Ref#modifyOr and Ref#updateOr
  core/shared/src/main/scala/cats/effect/concurrent/Ref.scala
  core/shared/src/test/scala/cats/effect/concurrent/RefTests.scala
Labels: enhancement

#925 Port concurrent ref
  build.sbt
  concurrent/shared/src/main/scala/cats/effect/concurrent/Ref.scala
  core/shared/src/test/scala/cats/effect/BaseSpec.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/LensRefSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/RefSpec.scala
Labels: CE 3

#923 Reimplemented IOFiber callbacks with a thread-safe atomic stack
  core/shared/src/main/scala/cats/effect/CallbackStack.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: CE 3

#933 Port concurrent deferred
  .jvmopts
  build.sbt
  concurrent/js/src/main/scala/cats/effect/internals/Logger.scala
  concurrent/js/src/main/scala/cats/effect/internals/TrampolineEC.scala
  concurrent/js/src/test/scala/cats/effect/internals/Platform.scala
  concurrent/jvm/src/main/scala/cats/effect/internals/Logger.scala
  concurrent/jvm/src/main/scala/cats/effect/internals/TrampolineEC.scala
  concurrent/jvm/src/test/scala/cats/effect/internals/Platform.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/ArrayStack.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/Deferred.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/internals/LinkedMap.scala
  concurrent/shared/src/main/scala/cats/effect/concurrent/internals/Trampoline.scala
  concurrent/shared/src/test/scala/cats/effect/concurrent/internals/LinkedMapSpec.scala
  concurrent/shared/src/test/scala/cats/effect/concurrent/internals/TestUtils.scala
  concurrent/shared/src/test/scala/cats/effect/concurrent/internals/TrampolineECSpec.scala
  core/jvm/src/test/scala/cats/effect/concurrent/DeferredJVMSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/DeferredSpec.scala
Labels: CE 3

#955 Updated all the stuff; fixed a ton of warnings
  .github/workflows/ci.yml
  build.sbt
  core/js/src/main/scala/cats/effect/IOCompanionPlatform.scala
  core/js/src/main/scala/cats/effect/IOPlatform.scala
  core/jvm/src/main/scala/cats/effect/IOPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SchedulerCompanionPlatform.scala
  core/jvm/src/test/scala/cats/effect/IOAppSpec.scala
  core/jvm/src/test/scala/cats/effect/concurrent/DeferredJVMSpec.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/UnsafeTimer.scala
  core/shared/src/test/scala/cats/effect/Runners.scala
  core/shared/src/test/scala/cats/effect/concurrent/LensRefSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/RefSpec.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncBracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncRegionTests.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/BracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentBracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentRegionTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentTests.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ManagedTests.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncEffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncManagedTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalBracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalRegionTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalTests.scala
  laws/shared/src/test/scala/cats/effect/ClockSpec.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
  project/plugins.sbt
  testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3

#959 Build a better bracket
  README.md
  concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
  core/shared/src/main/scala/cats/effect/BooleanArrayStack.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/package.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  core/shared/src/test/scala/cats/effect/Runners.scala
  hierarchy.svg
  kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Effect.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Managed.scala
  kernel/shared/src/main/scala/cats/effect/kernel/SyncEffect.scala
  kernel/shared/src/main/scala/cats/effect/kernel/SyncManaged.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Temporal.scala
  kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
  kernel/shared/src/main/scala/cats/effect/kernel/package.scala
  kernel/shared/src/main/scala/cats/effect/kernel/safe.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncBracketLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncBracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncRegionLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncRegionTests.scala
  laws/shared/src/main/scala/cats/effect/laws/BracketLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/BracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentBracketLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentBracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentRegionLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentRegionTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentTests.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ManagedLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ManagedTests.scala
  laws/shared/src/main/scala/cats/effect/laws/RegionLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/RegionTests.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncEffectLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncEffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncManagedLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncManagedTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalBracketLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalBracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalRegionLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalRegionTests.scala
  laws/shared/src/test/scala/cats/effect/BracketSpec.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/PureConcGenerators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3, discussion

#957 Align instance for parallelf
  kernel/shared/src/main/scala/cats/effect/instances/ConcurrentInstances.scala
  kernel/shared/src/main/scala/cats/effect/kernel/ParallelF.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
Labels: CE 3

#953 Exclusively use setTimeout for executor on JavaScript
  concurrent/shared/src/main/scala/cats/effect/concurrent/MVar.scala
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  core/shared/src/test/scala/cats/effect/concurrent/MVarSpec.scala
Labels: CE 3

#961 Uncancelable cancels
  core/shared/src/main/scala/cats/effect/IOFiber.scala
Labels: CE 3

#962 Fixed cancelation semantics to block when canceling uncancelable
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
Labels: CE 3

#963 Initial implementation of polyfill executor
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
Labels: CE 3

#968 Added ciFirefox to the build for running coreJS/test on geckodriver
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: CE 3

#960 Revise race pair
  benchmarks/src/main/scala/cats/effect/benchmarks/AsyncBenchmark.scala
  core/jvm/src/test/scala/cats/effect/concurrent/DeferredJVMSpec.scala
  core/shared/src/main/scala/cats/effect/CallbackStack.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/package.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  core/shared/src/test/scala/cats/effect/Runners.scala
  kernel/shared/src/main/scala/cats/effect/instances/ConcurrentInstances.scala
  kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentTests.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalTests.scala
  laws/shared/src/test/scala/cats/effect/PureConcSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3

#969 Implemented postMessage polyfill for setImmediate
  build.sbt
  core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
Labels: CE 3

#974 Protect racePair variants against fiber leaks with uncancelable
  core/shared/src/main/scala/cats/effect/IO.scala
  kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
Labels: CE 3

#978 Bring MVar on par with MVar2 from CE2
  concurrent/shared/src/main/scala/cats/effect/concurrent/MVar.scala
  core/shared/src/test/scala/cats/effect/concurrent/MVarSpec.scala
Labels: CE 3

#980 Initial sketch of Sync.blocking
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/test/scala/cats/effect/RunnersPlatform.scala
  core/jvm/src/test/scala/cats/effect/concurrent/DeferredJVMSpec.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
  core/shared/src/test/scala/cats/effect/Runners.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Sync.scala
  testkit/shared/src/main/scala/cats/effect/testkit/freeEval.scala
Labels: CE 3

#979 Port LiftIO to CE3
  core/shared/src/main/scala/cats/effect/LiftIO.scala
Labels: CE 3

#985 Fix non-determinism in MVar tests
  core/shared/src/test/scala/cats/effect/concurrent/MVarSpec.scala
Labels: CE 3

#984 Generalized Sync to arbitrary suspension hints
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Sync.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncEffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/SyncTests.scala
  laws/shared/src/test/scala/cats/effect/FreeSyncSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/Generators.scala
  testkit/shared/src/main/scala/cats/effect/testkit/freeEval.scala
Labels: CE 3

#971 Better JS app
  core/js/src/main/scala/cats/effect/IOApp.scala
  example/js/src/main/scala/cats/effect/example/Example.scala
  example/test-js.sh
Labels: CE 3

#976 More laws and cleanup
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentTests.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectTests.scala
  laws/shared/src/main/scala/cats/effect/laws/TemporalTests.scala
Labels: CE 3

#1000 Updated dotty (and some libraries)
  .github/workflows/ci.yml
  build.sbt
Labels: CE 3

#998 Backpressured cancels
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: CE 3

#1004 Preallocate closures in IO run loop
  core/shared/src/main/scala/cats/effect/IOFiber.scala
Labels: CE 3

#1005 A fiber can be a runnable
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
Labels: CE 3

#1007 Fix tryAcquireN when available permits == acquired permits
  concurrent/shared/src/main/scala/cats/effect/concurrent/Semaphore.scala
  core/shared/src/test/scala/cats/effect/concurrent/SemaphoreSpec.scala
Labels: CE 3

#1002 Added Concurrent#forceR and associated laws
  kernel/shared/src/main/scala/cats/effect/kernel/Effect.scala
  kernel/shared/src/main/scala/cats/effect/kernel/concurrent.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/ConcurrentSyntax.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/ConcurrentTests.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/EffectTests.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TimeT.scala
  testkit/shared/src/main/scala/cats/effect/testkit/freeEval.scala
  testkit/shared/src/main/scala/cats/effect/testkit/pure.scala
Labels: CE 3, laws

#1003 Transformer instances for sync
  kernel/shared/src/main/scala/cats/effect/kernel/Clock.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Sync.scala
  laws/shared/src/test/scala/cats/effect/BaseSpec.scala
  laws/shared/src/test/scala/cats/effect/ClockSpec.scala
  laws/shared/src/test/scala/cats/effect/FreeSyncSpec.scala
  testkit/shared/src/main/scala/cats/effect/testkit/freeEval.scala
Labels: CE 3

#1014 Resume fiber before initializing in exec
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  laws/shared/src/test/scala/cats/effect/FreeSyncSpec.scala
Labels: CE 3

#1012 Read callback once before invoking
  core/shared/src/main/scala/cats/effect/CallbackStack.scala
Labels: CE 3

#1013 Remove IOCont and split continuation functions into success and failure
  core/shared/src/main/scala/cats/effect/IOCont.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
Labels: CE 3

#1022 Reset cancel effect at done
  core/shared/src/main/scala/cats/effect/IOFiber.scala
Labels: CE 3
