Repository typelevel/cats-effect, pull requests merged in 2021-06, with the labels that each got.

#2025 Update sbt to 1.5.3
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2029 Update sbt-jmh to 0.4.3
  project/plugins.sbt
Labels: :older_man: CE2, dependencies

#2028 Update sbt to 1.5.3
  project/build.properties
  scalafix/project/build.properties
Labels: :older_man: CE2, dependencies

#2026 Update sbt-jmh to 0.4.3
  project/plugins.sbt
Labels: dependencies

#2031 Use proper cats-effect versions in scalafix tests
  scalafix/build.sbt
Labels: :older_man: CE2

#2052 Update sbt-scalajs, scalajs-library, ... to 1.6.0
  project/plugins.sbt
Labels: dependencies

#2053 Update sbt-scalajs to 1.6.0
  project/plugins.sbt
Labels: :older_man: CE2, dependencies

#2057 Update specs2-core, specs2-scalacheck to 4.12.1
  build.sbt
Labels: dependencies

#2059 Update sbt to 1.5.4
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2060 Update sbt to version 1.5.4
  project/build.properties
  scalafix/project/build.properties
Labels: :older_man: CE2

#2075 Update specs2-core, specs2-scalacheck to 4.12.2
  build.sbt
Labels: dependencies

#2086 Remove the unused docs mergify config
  .mergify.yml
Labels: :books: docs

#2089 Rename scala variable names in build
  build.sbt
Labels: :older_man: CE2
