Repository typelevel/cats-effect, pull requests merged in 2021-04, with the labels that each got.

#1836 Add IO#unsafeToFutureCancelable
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :hammer: forward incompatible

#1882 Update sbt to 1.5.0
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#1885 Update sbt to 1.5.0
  project/build.properties
Labels: :older_man: CE2

#1894 Fix incorrect scheduling of fibers on the work stealing runtime in presence of parasitic execution contexts
  core/js/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/HelperThread.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  tests/jvm/src/test/scala/cats/effect/ParasiticECSpec.scala
  tests/shared/src/test/scala/cats/effect/IOPropSpec.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :beetle: bug

#1896 Add testing to sidebars
  docs/guides/testing.md
  site-docs/sidebars.json
Labels: :books: docs, :older_man: CE2

#1850 Add Random materializers for monad transformers
  std/shared/src/main/scala/cats/effect/std/Random.scala
Labels: :hammer: forward incompatible

#1919 Update sbt-mdoc to 2.2.20
  project/plugins.sbt
Labels: dependencies

#1926 Updates to the sbt plugins
  project/plugins.sbt
Labels: :older_man: CE2

#1925 Update specs2-core, specs2-scalacheck to 4.11.0
  build.sbt
Labels: dependencies

#1879 'Dealing with cancelation' section rewritten
  docs/tutorial.md
Labels: :books: docs

#1931 Update sbt to 1.5.1
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies
