Repository typelevel/cats-effect, pull requests merged in 2021-02, with the labels that each got.

#1650 Added unidoc to the build
  build.sbt
  kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Fiber.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
  kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  project/plugins.sbt
  std/shared/src/main/scala/cats/effect/std/Console.scala
  std/shared/src/main/scala/cats/effect/std/Supervisor.scala
Labels: docs

#1648 Rewrote the readme
  README.md
  cats-effect-logo.png
  contention.png
Labels: docs

#1670 Fix supervisor cleanup race
  std/shared/src/main/scala/cats/effect/std/Supervisor.scala
Labels: :beetle: bug

#1679 Fixed Firefox build aliases
  build.sbt
Labels: :gear: infrastructure

#1705 Update sbt-mdoc to 2.2.18
  project/plugins.sbt
Labels: dependencies

#1704 Update better-monadic-for to 0.3.1
  project/Common.scala
Labels: dependencies

#1706 Update scalafmt-core to 2.6.4
  .scalafmt.conf
  build.sbt
  project/Common.scala
  project/plugins.sbt
  std/shared/src/main/scala/cats/effect/std/Semaphore.scala
Labels: dependencies

#1707 Update scalafmt-core to 2.7.5
  .scalafmt.conf
  kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
  kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
  tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
  tests/shared/src/test/scala/cats/effect/Runners.scala
  tests/shared/src/test/scala/cats/effect/kernel/DeferredSpec.scala
  tests/shared/src/test/scala/cats/effect/std/CountDownLatchSpec.scala
  tests/shared/src/test/scala/cats/effect/std/HotswapSpec.scala
  tests/shared/src/test/scala/cats/effect/std/QueueSpec.scala
  tests/shared/src/test/scala/cats/effect/std/internal/BinomialHeapSpec.scala
Labels: dependencies

#1737 Update sbt-spiewak-sonatype to 0.20.4
  project/plugins.sbt
Labels: dependencies

#1740 Consolidated IORuntime configuration and enabled access in IOApp itself
  benchmarks/src/main/scala/cats/effect/benchmarks/WorkStealingBenchmark.scala
  core/js/src/main/scala/cats/effect/IOApp.scala
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeConfigCompanionPlatform.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TestInstances.scala
  tests/jvm/src/test/scala/cats/effect/RunnersPlatform.scala
  tests/jvm/src/test/scala/cats/effect/std/DeferredJVMSpec.scala
Labels: :bike: :house:

#1743 Copied over (and loosely adapted) scaladoc from CE2 IO
  core/jvm/src/main/scala/cats/effect/IOPlatform.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  std/shared/src/main/scala/cats/effect/std/Console.scala
  std/shared/src/main/scala/cats/effect/std/Dequeue.scala
  std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
  std/shared/src/main/scala/cats/effect/std/Queue.scala
  std/shared/src/main/scala/cats/effect/std/Semaphore.scala
  std/shared/src/main/scala/cats/effect/std/Supervisor.scala
Labels: :books: docs
