Repository typelevel/cats-effect, pull requests merged in 2021-07, with the labels that each got.

#2094 Update sbt-scalajs-crossproject to 1.1.0
  project/plugins.sbt
Labels: dependencies

#2099 Update specs2-core, specs2-scalacheck to 4.12.3
  build.sbt
Labels: dependencies

#2100 Remove silencer from the build
  build.sbt
  core/shared/src/main/scala/cats/effect/concurrent/MVar.scala
Labels: :older_man: CE2

#2101 Override `map2Eval` for `IO`
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/shared/src/test/scala/cats/effect/KleisliIOSpec.scala
Labels: :beetle: bug

#2097 Use automatic unmanaged source directory handling
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/ECBenchmark.scala
  build.sbt
  core/shared/src/main/scala-2.13/cats/effect/ResourceLike.scala
  core/shared/src/main/scala-3/cats/effect/ResourceLike.scala
  project/plugins.sbt
Labels: :older_man: CE2

#2106 Documented giter8 template
  README.md
  docs/getting-started.md
Labels: :books: docs

#2110 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependencies

#2111 Update scala3-library, ... to 3.0.1
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2112 Update Scala to version 3.0.1
  .github/workflows/ci.yml
  build.sbt
Labels: :older_man: CE2, dependencies

#2121 Update sbt to 1.5.5
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2122 Update sbt to version 1.5.5
  project/build.properties
  scalafix/project/build.properties
Labels: :older_man: CE2, dependencies

#2114 Added private functions for resetting the global runtime
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
Labels: :bike: :house:

#2128 Cats Effect 3 tracing docs
  docs/tracing.md
Labels: :books: docs

#2137 Update sbt-scalafix to 0.9.29
  scalafix/project/plugins.sbt
Labels: :older_man: CE2

#2138 Update sbt-mdoc to 2.2.22
  project/plugins.sbt
Labels: dependencies

#2139 Update sbt-mdoc to 2.2.22
  project/plugins.sbt
Labels: :older_man: CE2, dependencies

#2132 More scaladoc
  build.sbt
  core/js/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/ResourceApp.scala
Labels: :books: docs

#2140 Added conceptual documentation and general introduction
  docs/concepts.md
  site-docs/sidebars.json
Labels: :books: docs

#2151 Updated documentation version for 3.2.0
  README.md
  docs/getting-started.md
  docs/tutorial.md
Labels: :books: docs

#2149 Add tracing to sidebar
  site-docs/sidebars.json
Labels: :books: docs

#2154 Some light cleanup on the concepts page
  docs/concepts.md
Labels: :books: docs

#1817 Backpressure Interface for CE3
  std/shared/src/main/scala/cats/effect/std/Backpressure.scala
  tests/shared/src/test/scala/cats/effect/std/BackpressureSpec.scala
Labels: :mushroom: enhancement

#2157 Kleisli `parTraverse` CE2
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Resource.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
  laws/shared/src/test/scala/cats/effect/ResourceTests.scala
Labels: :older_man: CE2

#2169 `IO.suspend` -> `IO.defer`
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/SyncIO.scala
  core/shared/src/main/scala/cats/effect/internals/CancelUtils.scala
  core/shared/src/main/scala/cats/effect/internals/IOBracket.scala
  core/shared/src/main/scala/cats/effect/internals/IOConnection.scala
  docs/datatypes/io.md
  docs/datatypes/ioapp.md
  laws/jvm/src/test/scala/cats/effect/IOJVMTests.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
  laws/shared/src/test/scala/cats/effect/SyncIOTests.scala
  runtime-tests/src/fulltracing/scala/cats/effect/FullStackTracingTests.scala
  scalafix/.bsp/sbt.json
  scalafix/build.sbt
  scalafix/rules/src/main/scala/fix/v2_5_2.scala
  scalafix/v2_5_2/input/src/main/scala/fix/IORewrites.scala
  scalafix/v2_5_2/input/src/main/scala/fix/SyncIORewrites.scala
  scalafix/v2_5_2/output/src/main/scala/fix/IORewrites.scala
  scalafix/v2_5_2/output/src/main/scala/fix/SyncIORewrites.scala
  scalafix/v2_5_2/tests/src/test/scala/fix/V252Tests.scala
Labels: :older_man: CE2

#2182 Misc changes for release
  build.sbt
  core/js/src/main/scala/cats/effect/unsafe/PolyfillExecutionContext.scala
Labels: :gear: infrastructure

#2183 Updated docs for 3.2.1 release
  README.md
  docs/getting-started.md
  docs/tutorial.md
Labels: :books: docs

#2184 Updated front page version
  website/pages/en/index.js
Labels: :books: docs
