Repository typelevel/cats-effect, pull requests merged in 2021-11, with the labels that each got.

#2485 Update scala-library to 2.13.7 in series/2.x
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2486 Update scala-library to 2.13.7 in series/3.x
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2496 Improve caching in the docs workflow
  .github/workflows/microsite.yml
Labels: :books: docs

#2497 Cherry pick documentation changes
  CODE_OF_CONDUCT.md
  README.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/scaling-and-tuning/system-properties.md
  docs/schedulers.md
  docs/std/dispatcher.md
  docs/std/supervisor.md
  docs/thread-model.md
  docs/tutorial.md
  docs/typeclasses/async.md
  site-docs/sidebars.json
Labels: :books: docs

#2526 Update scalafmt-core to 3.1.0 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2538 Update scalafmt-core to 3.1.1 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
  scalafix/build.sbt
Labels: dependencies

#2522 Documentation for `TestControl` and core runtime reorg
  docs/core/test-runtime.md
  site-docs/sidebars.json
Labels: :books: docs

#2559 Update sbt-java-formatter to 0.7.0 in series/3.x
  build.sbt
  project/plugins.sbt
Labels: dependencies

#2564 Update sbt-scalafmt to 2.4.4 in series/2.x
  project/plugins.sbt
Labels: dependencies

#2565 Update sbt-scalafmt to 2.4.4 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2571 Update scalafmt-core to 3.1.2 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2576 Add instructions about source maps
  docs/tracing.md
Labels: :books: docs

#2583 Update specs2-core, specs2-scalacheck to 4.13.1 in series/3.x
  build.sbt
Labels: dependencies

#2585 Update discipline-specs2 to 1.2.5 in series/3.x
  build.sbt
Labels: dependencies

#2591 Update readme and docs for 3.3.0
  README.md
  docs/getting-started.md
  docs/tutorial.md
Labels: :books: docs

#2594 Update cats-core, cats-laws to 2.7.0 in series/2.x
  build.sbt
Labels: dependencies

#2598 Updated scastie to use 3.3.0
  website/pages/en/index.js
Labels: :books: docs

#2605 Bumped the base version to account for the Cats update
  build.sbt
Labels: :older_man: CE2

#2614 Update scalafmt-core to 3.2.0 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies
