Repository typelevel/cats-effect, pull requests merged in 2021-08, with the labels that each got.

#2180 Small CI optimizations
  .github/workflows/ci.yml
  build.sbt
  example/test-jvm.sh
Labels: :gear: infrastructure

#2192 Update sbt-scalajs, scalajs-compiler, ... to 1.7.0
  project/plugins.sbt
Labels: dependencies

#2198 Cancel 2.5.2
  .gitignore
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/SyncIO.scala
  docs/getting-started.md
  docs/guides/tutorial.md
  scalafix/.bsp/sbt.json
  scalafix/README.md
  scalafix/build.sbt
  scalafix/rules/src/main/scala/fix/v2_5_3.scala
  scalafix/v2_5_3/input/src/main/scala/fix/IORewrites.scala
  scalafix/v2_5_3/input/src/main/scala/fix/SyncIORewrites.scala
  scalafix/v2_5_3/output/src/main/scala/fix/IORewrites.scala
  scalafix/v2_5_3/output/src/main/scala/fix/SyncIORewrites.scala
  scalafix/v2_5_3/tests/src/test/scala/fix/V253Tests.scala
Labels: :older_man: CE2

#2194 Update sbt-scalajs to version 1.7.0
  project/plugins.sbt
Labels: dependencies, :older_man: CE2

#2206 Updated documentation versions for 3.2.2
  README.md
  docs/getting-started.md
  docs/tutorial.md
Labels: :books: docs

#2209 Updated main page for 3.2.2
  website/pages/en/index.js
Labels: :books: docs

#2210 Swapped scastie build configuration back to 2.13
  website/pages/en/index.js
Labels: :books: docs

#2212 Autogenerate CI commands
  build.sbt
  project/CI.scala
  project/JSEnv.scala
Labels: :gear: infrastructure

#2213 Add `cats.effect.std.Random` doc page
  docs/std/random.md
  site-docs/sidebars.json
Labels: :books: docs

#2215 Update scalajs-env-selenium to 1.1.1
  project/plugins.sbt
Labels: dependencies

#2226 Fix cached tracing for `IO.delay`
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Thunk.scala
  tests/jvm/src/test/scala/cats/effect/tracing/TracingSpec.scala
  tests/shared/src/test/scala/cats/effect/ThunkSpec.scala
Labels: :beetle: bug

#2228 Backport thunk
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/Thunk.scala
  core/shared/src/test/scala/cats/effect/ThunkSpec.scala
Labels: :older_man: CE2

#2230 Add cached tracing support for `IO.delay` and `IO.defer`
  build.sbt
  core/shared/src/main/scala/cats/effect/Async.scala
  core/shared/src/main/scala/cats/effect/Concurrent.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/internals/IORunLoop.scala
  core/shared/src/test/scala/cats/effect/ThunkSpec.scala
  runtime-tests/src/test/scala/cats/effect/CachedStackTracingTests.scala
Labels: :older_man: CE2

#2274 Updated docs for 3.2.5
  README.md
  docs/getting-started.md
  docs/tutorial.md
Labels: :books: docs

#2277 CE2 build updates
  .github/workflows/ci.yml
  .github/workflows/clean.yml
  build.sbt
  project/plugins.sbt
Labels: :older_man: CE2

#2282 Update specs2-core, specs2-scalacheck to 4.12.6
  build.sbt
Labels: dependencies
