Repository typelevel/cats-effect, pull requests merged in 2021-12, with the labels that each got.

#2618 Update sbt-spiewak-sonatype to 0.23.0 in series/2.x
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: dependencies

#2622 Update scalafmt-core to 3.2.1 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2624 Update sbt-scalafmt to 2.4.5 in series/2.x
  project/plugins.sbt
Labels: dependencies

#2625 Update sbt-scalafmt to 2.4.5 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2640 Update sbt to 1.5.6 in series/2.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2641 Update sbt to 1.5.6 in series/3.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2652 Update sbt to 1.5.7 in series/2.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2653 Update sbt to 1.5.7 in series/3.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2619 Update sbt-spiewak-sonatype to 0.23.0 in series/3.x
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: dependencies

#2613 Sync run convenience function
  build.sbt
  core/js/src/main/scala/cats/effect/IOPlatform.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :mushroom: enhancement, :bike: :house:, :exclamation: source breaking :exclamation:

#2675 Updated site for 3.3.1
  website/pages/en/index.js
Labels: :books: docs

#2677 Update sbt to 1.5.8 in series/2.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2686 Update scalafmt-core to 3.2.2 in series/3.x
  .scalafmt.conf
  core/shared/src/main/scala/cats/effect/IO.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Sync.scala
  scalafix/.scalafmt.conf
Labels: dependencies

#2689 Update sbt-scalafmt to 2.4.6 in series/2.x
  project/plugins.sbt
Labels: dependencies

#2690 Update sbt-scalafmt to 2.4.6 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2691 Update scalafmt-core to 3.3.0 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2694 Update sbt to 1.6.0 in series/2.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2696 Update sbt to 1.6.1 in series/2.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2705 Detect sbt thread cleaner and terminate workers
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  tests/js/src/main/scala/catseffect/examplesplatform.scala
  tests/jvm/src/test/scala/cats/effect/IOAppSpec.scala
  tests/shared/src/main/scala/catseffect/examples.scala
Labels: :beetle: bug
