Repository typelevel/cats-effect, pull requests merged in 2021-09, with the labels that each got.

#2207 Implement tracing for JS
  .github/workflows/ci.yml
  build.sbt
  core/js/src/main/scala/cats/effect/tracing/TracingConstants.scala
  core/js/src/main/scala/cats/effect/tracing/TracingPlatform.scala
  core/jvm/src/main/scala/cats/effect/tracing/TracingPlatform.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/tracing/Tracing.scala
  package-lock.json
  package.json
  project/CI.scala
  tests/js/src/test/scala/cats/effect/unsafe/StripedHashtableSpec.scala
  tests/shared/src/test/scala/cats/effect/IOPropSpec.scala
  tests/shared/src/test/scala/cats/effect/std/DequeueSpec.scala
  tests/shared/src/test/scala/cats/effect/std/PQueueSpec.scala
  tests/shared/src/test/scala/cats/effect/tracing/TraceSpec.scala
  tests/shared/src/test/scala/cats/effect/tracing/TracingSpec.scala
Labels: :mushroom: enhancement

#2288 Updated Gitter links to Discord
  CODE_OF_CONDUCT.md
  README.md
  docs/migration-guide.md
Labels: :books: docs

#2290 Update scala3-library, ... to 3.0.2
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2297 Remove the unused mergify rule
  .mergify.yml
Labels: :gear: infrastructure

#2296 Update specs2-core, specs2-scalacheck to 4.12.8
  build.sbt
Labels: dependencies

#2295 Update Scala 3 to version 3.0.2
  .github/workflows/ci.yml
  build.sbt
Labels: :older_man: CE2

#2301 Update specs2-core, specs2-scalacheck to 4.12.9
  build.sbt
Labels: dependencies

#2313 Update specs2-core, specs2-scalacheck to 4.12.10
  build.sbt
Labels: dependencies

#2331 Update specs2-core, specs2-scalacheck to 4.12.11
  build.sbt
Labels: dependencies

#2330 Update the scastie link for CE 3.2.8
  website/pages/en/index.js
Labels: :books: docs

#2334 Update specs2-core, specs2-scalacheck to 4.12.12
  build.sbt
Labels: dependencies

#2346 Update scala-js-macrotask-executor to 0.2.0
  build.sbt
Labels: dependencies

#2352 Update sbt-spiewak-sonatype to 0.22.1
  project/plugins.sbt
Labels: dependencies

#2353 Update Scala 2.12
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: :older_man: CE2

#2351 Update scala-library to 2.12.15
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2357 Update the scastie link for 3.2.9
  website/pages/en/index.js
Labels: :books: docs

#2356 Update Cats Effect version strings in docs
  README.md
  docs/getting-started.md
  docs/tutorial.md
Labels: :books: docs

#2355 Update scalafmt-core to 3.0.4
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2276 Added `TestControl`, with first-class support for time mocking
  build.sbt
  core/shared/src/main/scala/cats/effect/IO.scala
  example/js/src/main/scala/cats/effect/example/Example.scala
  kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TestInstances.scala
  tests/jvm/src/test/scala/cats/effect/ParasiticECSpec.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
  tests/shared/src/test/scala/cats/effect/MemoizeSpec.scala
  tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
  tests/shared/src/test/scala/cats/effect/std/BackpressureSpec.scala
  tests/shared/src/test/scala/cats/effect/testkit/TestControlSpec.scala
Labels: :mushroom: enhancement, :exclamation: source breaking :exclamation:

#2370 Switch to the typelevel jdk index
  .github/workflows/ci.yml
  build.sbt
Labels: :gear: infrastructure, :older_man: CE2

#2369 Switch to the typelevel jdk index
  .github/workflows/ci.yml
  build.sbt
Labels: :gear: infrastructure
