Repository typelevel/cats-effect, pull requests merged in 2021-05, with the labels that each got.

#1880 Use latest JDKs in CI
  .github/workflows/ci.yml
  build.sbt
Labels: :gear: infrastructure

#1936 Update scalacheck to 1.15.4
  build.sbt
Labels: dependencies

#1949 Fix sbt 1.5 deprecated syntax and warnings in build
  build.sbt
Labels: :older_man: CE2

#1954 Update sbt to 1.5.2
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#1960 Update sbt-jmh to 0.4.1
  project/plugins.sbt
Labels: dependencies

#1961 Update sbt-jmh to 0.4.1
  project/plugins.sbt
Labels: :older_man: CE2

#1962 Update sbt-jmh to 0.4.2
  project/plugins.sbt
Labels: dependencies

#1966 Scala 3.0.0 final [CE2]
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: :older_man: CE2

#1968 Update to sbt 1.5.2
  project/build.properties
Labels: :older_man: CE2

#1969 Update to sbt-jmh 0.4.2
  project/plugins.sbt
Labels: :older_man: CE2

#1972 Update sbt-mdoc to 2.2.21
  project/plugins.sbt
Labels: dependencies

#1987 Update specs2-core, specs2-scalacheck to 4.12.0
  build.sbt
Labels: dependencies

#1985 Scala 3 build warnings fixes
  .github/workflows/ci.yml
  build.sbt
  core/shared/src/main/scala/cats/effect/Resource.scala
  core/shared/src/test/scala/cats/effect/concurrent/DeferredTests.scala
  docs/concurrency/overview.md
  docs/datatypes/contextshift.md
  docs/datatypes/resource.md
  docs/guides/testing.md
  docs/guides/tutorial.md
  project/plugins.sbt
  scalafix/build.sbt
  scalafix/project/build.properties
  scalafix/project/plugins.sbt
  scalafix/v2_4_0/tests/src/test/scala/fix/CatsEffectTests.scala
Labels: :older_man: CE2

#1983 Replace silenceSystemErr hack with a generated silent exception
  core/shared/src/test/scala/cats/effect/CatsEffectSuite.scala
  core/shared/src/test/scala/cats/effect/IOAppTests.scala
  core/shared/src/test/scala/cats/effect/internals/TestUtils.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/arbitrary.scala
Labels: :older_man: CE2

#1990 Update Scala to 2.13.6
  .github/workflows/ci.yml
  build.sbt
  project/plugins.sbt
Labels: :older_man: CE2

#1976 Update scala-library to 2.13.6
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#1998 Add a more explicit relative link to other markdown files
  docs/datatypes/index.md
  docs/datatypes/io.md
  docs/datatypes/ioapp.md
  docs/datatypes/syncio.md
  docs/datatypes/timer.md
  docs/typeclasses/concurrent-effect.md
Labels: :books: docs, :older_man: CE2

#2003 Revert the relative links to their original form
  docs/datatypes/index.md
  docs/datatypes/io.md
  docs/datatypes/ioapp.md
  docs/datatypes/syncio.md
  docs/datatypes/timer.md
  docs/typeclasses/concurrent-effect.md
Labels: :books: docs, :older_man: CE2

#2004 Rename the installation page to match its id
  docs/getting-started.md
Labels: :books: docs, :older_man: CE2

#2006 Fix old sbt syntax in scalafix subproject
  scalafix/build.sbt
Labels: :older_man: CE2

#2007 Hide the silent throwable arbitrary instance
  laws/shared/src/main/scala/cats/effect/laws/discipline/arbitrary.scala
  laws/shared/src/test/scala/cats/effect/IOTests.scala
Labels: :beetle: bug, :older_man: CE2

#2009 Update docusaurus to version 1.14.7
  .github/workflows/microsite.yml
  website/package.json
Labels: :books: docs

#2014 Update scala-library to 2.12.14
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
Labels: dependencies

#2016 Update Scala to 2.12.14
  .github/workflows/ci.yml
  build.sbt
Labels: :older_man: CE2, dependencies

#2017 Tie the silencer-lib dotty compat version to the latest Scala 2.13 release
  build.sbt
Labels: :older_man: CE2, dependencies
