Repository typelevel/cats-effect, pull requests merged in 2021-03, with the labels that each got.

#1766 Update sbt to 1.4.8
  project/build.properties
Labels: dependencies

#1774 Update sbt to 1.4.9
  project/build.properties
Labels: dependencies

#1800 Opened uncancelable region to the right
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/Generators.scala
  kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
  laws/shared/src/main/scala/cats/effect/laws/GenSpawnLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/GenSpawnTests.scala
  laws/shared/src/main/scala/cats/effect/laws/GenTemporalTests.scala
  laws/shared/src/main/scala/cats/effect/laws/MonadCancelLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/MonadCancelTests.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TestInstances.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
  tests/shared/src/test/scala/cats/effect/OptionTIOSpec.scala
  tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
Labels: laws

#1801 Getting ready for a new CE2 release
  .github/workflows/ci.yml
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/ECBenchmark.scala
  benchmarks/shared/src/main/scala/cats/effect/benchmarks/RefBenchmark.scala
  build.sbt
  core/shared/src/main/scala/cats/effect/syntax/ParallelNSyntax.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/BracketTests.scala
  laws/shared/src/main/scala/cats/effect/laws/discipline/arbitrary.scala
  laws/shared/src/test/scala/cats/effect/FiberTests.scala
  project/build.properties
  project/plugins.sbt
Labels: :older_man: CE2

#1829 Fixed several extremely rare race conditions in runloop resumption
  core/js/src/main/scala/cats/effect/IOFiberPlatform.scala
  core/jvm/src/main/scala/cats/effect/IOFiberPlatform.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :beetle: bug

#1851 [CE2] Scala 3.0.0-RC2
  .github/workflows/ci.yml
  build.sbt
Labels: :older_man: CE2

#1852 Update sbt-mdoc to 2.2.19
  project/plugins.sbt
Labels: dependencies

#1865 Update sbt-scalajs, scalajs-compiler, ... to 1.5.1
  project/plugins.sbt
Labels: dependencies
