Repository typelevel/cats-effect, pull requests merged in 2022-03, with the labels that each got.

#2732 Expose an `IOApp#MainThread` executor
  build.sbt
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  tests/js/src/main/scala/catseffect/examplesplatform.scala
  tests/jvm/src/main/scala/catseffect/examplesplatform.scala
  tests/jvm/src/test/scala/cats/effect/IOAppSpec.scala
Labels: :mushroom: enhancement

#2359 Add embedError convenience function
  kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
Labels: :mushroom: enhancement

#2749 Adds CommutativeApplicative instance for Resource.Par
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  tests/shared/src/test/scala/cats/effect/kernel/ParallelFSpec.scala
Labels: :mushroom: enhancement

#2894 Update versions for 3.3.8
  website/pages/en/index.js
Labels: :books: docs

#2892 Updated versions for 3.3.8
  README.md
  docs/core/test-runtime.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/tutorial.md
Labels: :books: docs

#2912 Update site for 3.3.9
  website/pages/en/index.js
Labels: :books: docs

#2900 Update sbt-scalajs-crossproject to 1.2.0 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2899 Update sbt-scalajs-crossproject to 1.2.0 in series/2.x
  project/plugins.sbt
Labels: dependencies

#2921 Update sbt-mdoc to 2.3.2 in series/2.x
  project/plugins.sbt
Labels: dependencies
