Repository typelevel/cats-effect, pull requests merged in 2022-04, with the labels that each got.

#2924 Update specs2-core, specs2-scalacheck to 4.15.0 in series/3.x
  build.sbt
Labels: dependencies

#2934 Update scalafmt-core to 3.5.0 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2935 Resolved issue with fatal errors being eaten
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  tests/js/src/main/scala/catseffect/examplesplatform.scala
  tests/jvm/src/test/scala/cats/effect/IOAppSpec.scala
  tests/shared/src/main/scala/catseffect/RawApp.scala
  tests/shared/src/main/scala/catseffect/examples.scala
Labels: :beetle: bug

#2936 Updated versions for 3.3.10
  README.md
  docs/core/test-runtime.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/tutorial.md
Labels: :books: docs

#2948 Update site for 3.3.11
  website/pages/en/index.js
Labels: :books: docs

#2949 Update scalafmt-core to 3.5.1 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2951 Implemented configurability for `Supervisor` scope termination
  build.sbt
  std/shared/src/main/scala/cats/effect/std/Supervisor.scala
  tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
Labels: :mushroom: enhancement

#2952 Update sbt-scalafix to 0.10.0 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2964 Added some sbt-git workarounds
  build.sbt
Labels: :books: docs

#2968 Update scalafmt-core to 3.5.2 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies
