Repository typelevel/cats-effect, pull requests merged in 2022-02, with the labels that each got.

#2794 Update sbt to 1.6.2 in series/2.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2795 Update sbt to 1.6.2 in series/3.x
  project/build.properties
  scalafix/project/build.properties
Labels: dependencies

#2796 Fix link to fiber dumps in native image documentation
  docs/core/native-image.md
Labels: :books: docs

#2657 Introduce `IORuntimeBuilder`
  core/js/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
Labels: :mushroom: enhancement

#2770 Update scalafmt-core to 3.3.3 in series/3.x
  .scalafmt.conf
  core/shared/src/main/scala/cats/effect/IO.scala
  scalafix/.scalafmt.conf
  std/js/src/main/scala/cats/effect/std/Console.scala
  std/jvm/src/main/scala/cats/effect/std/Console.scala
Labels: dependencies

#2813 Update scalafmt-core to 3.4.2 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2821 Update scalafmt-core to 3.4.3 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2824 Update specs2-core, specs2-scalacheck to 4.13.3 in series/3.x
  build.sbt
Labels: dependencies

#2830 Update specs2-core, specs2-scalacheck to 4.14.0 in series/3.x
  build.sbt
Labels: dependencies

#2832 Update sbt-buildinfo to 0.11.0 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2841 Swapped out setup-scala for setup-java
  .github/workflows/microsite.yml
Labels: :books: docs

#2835 Add `Async#syncStep`
  core/shared/src/main/scala/cats/effect/IO.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  kernel/shared/src/main/scala/cats/effect/kernel/syntax/AsyncSyntax.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncLaws.scala
  laws/shared/src/main/scala/cats/effect/laws/AsyncTests.scala
Labels: :mushroom: enhancement, laws

#2848 Updated versions to 3.3.6
  README.md
  docs/core/test-runtime.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/tutorial.md
Labels: :books: docs
