Repository typelevel/cats-effect, pull requests merged in 2022-01, with the labels that each got.

#2645 Update sbt-scalajs, scalajs-compiler, ... to 1.8.0 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2711 Updated site for 3.3.3 release
  website/pages/en/index.js
Labels: :books: docs

#2670 Add batch offer/take methods to Queue and Dequeue
  std/shared/src/main/scala/cats/effect/std/Dequeue.scala
  std/shared/src/main/scala/cats/effect/std/Queue.scala
  tests/shared/src/test/scala/cats/effect/std/DequeueSpec.scala
  tests/shared/src/test/scala/cats/effect/std/QueueSpec.scala
Labels: :exclamation: source breaking :exclamation:

#2723 Update scalafmt-core to 3.3.1 in series/3.x
  .scalafmt.conf
  scalafix/.scalafmt.conf
Labels: dependencies

#2740 Updated versions in docs
  docs/core/test-runtime.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/tutorial.md
Labels: :books: docs

#2747 Update sbt-scalafix to 0.9.34 in series/3.x
  project/plugins.sbt
Labels: dependencies

#2755 Update specs2-core, specs2-scalacheck to 4.13.2 in series/3.x
  build.sbt
Labels: dependencies

#2753 Update scala-library to 2.13.8 in series/2.x
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2754 Update scala-library to 2.13.8 in series/3.x
  .github/workflows/ci.yml
  build.sbt
Labels: dependencies

#2758 Broke out contributing guidelines into a separate document
  CONTRIBUTING.md
  README.md
Labels: :books: docs

#2781 Remove repeated CE2 dispatcher qualification
  docs/std/dispatcher.md
Labels: :books: docs
