Repository typelevel/cats-effect, pull requests merged in 2022-06, with the labels that each got.

#3011 Disable tracing for browsers by default on JS
  core/js/src/main/scala/cats/effect/tracing/TracingConstants.scala
  tests/js/src/test/scala/cats/effect/exports.scala
Labels: discussion

#2869 Added support for configuring compute pool error reporter
  benchmarks/src/main/scala/cats/effect/benchmarks/WorkStealingBenchmark.scala
  build.sbt
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeBuilderPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
Labels: :mushroom: enhancement

#2464 Incorporate MapRef into Std
  std/js/src/main/scala/cats/effect/std/MapRefCompanionPlatform.scala
  std/jvm/src/main/scala/cats/effect/std/MapRefCompanionPlatform.scala
  std/shared/src/main/scala/cats/effect/std/MapRef.scala
  tests/jvm/src/test/scala/cats/effect/std/MapRefJVMSpec.scala
  tests/shared/src/test/scala/cats/effect/std/MapRefSpec.scala
Labels: :mushroom: enhancement

#3056 Added scaladoc for `IO.cede` and enhanced `GenSpawn#cede`
  core/shared/src/main/scala/cats/effect/IO.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
Labels: :books: docs

#3060 Updated versions for 3.3.13
  README.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/tutorial.md
Labels: :books: docs
