Repository typelevel/cats-effect, pull requests merged in 2023-01, with the labels that each got.

#3354 update the ref example
  docs/std/ref.md
Labels: :books: docs

#3355 Encourage alternatives to `IOApp` for browser apps
  core/js/src/main/scala/cats/effect/IOApp.scala
Labels: :books: docs

#3365 Bypass `IO`-specialized `Deferred` for now
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :beetle: bug

#3369 Updated site for 3.4.5
  website/pages/en/index.js
Labels: :books: docs

#3219 Integrated timers
  benchmarks/src/main/scala/cats/effect/benchmarks/SleepBenchmark.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/SleepDrift.scala
  benchmarks/src/main/scala/cats/effect/benchmarks/WorkStealingBenchmark.scala
  core/js-native/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SleepCallback.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SleepersQueue.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
  tests/jvm/src/test/scala/cats/effect/RunnersPlatform.scala
  tests/jvm/src/test/scala/cats/effect/unsafe/SleepCallbackSpec.scala
  tests/jvm/src/test/scala/cats/effect/unsafe/StripedHashtableSpec.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :microscope: experiment
