Repository typelevel/cats-effect, pull requests merged in 2023-09, with the labels that each got.

#3796 Cirrus CI cutbacks ...
  .cirrus.yml
Labels: :gear: infrastructure

#3798 Remove plugins we get transitively
  project/plugins.sbt
Labels: :gear: infrastructure

#3769 Update `reportFailure` scaladoc - add explanation of an unhandled errror.
  core/jvm/src/main/scala/cats/effect/IOApp.scala
Labels: :books: docs

#3766 Update users.js add ubilab.io
  website/pages/en/users.js
Labels: :books: docs

#3774 Print warning when we detect a non-main-thread main
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  docs/core/io-runtime-config.md
Labels: :mushroom: enhancement

#3822 Optimize `Dispatcher#unsafeRunAsync/unsafeRunAndForget`
  std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
Labels: :beetle: bug

#3831 Drop macOS jobs from Cirrus
  .cirrus.yml
Labels: :gear: infrastructure

#3832 Drop macOS jobs from Cirrus
  .cirrus.yml
Labels: :gear: infrastructure

#3800 Fix `Hotswap#get` being blocked by `Hotswap#swap`
  std/shared/src/main/scala/cats/effect/std/Hotswap.scala
  tests/shared/src/test/scala/cats/effect/std/HotswapSpec.scala
Labels: :beetle: bug

#3843 Updated versions script to look for `**` pattern
  README.md
  scripts/update-versions.sh
Labels: :gear: infrastructure

#3847 Try quoting labels in release notes config
  .github/release.yml
Labels: :gear: infrastructure

#3794 Join worker threads on pool shutdown
  benchmarks/src/main/scala/cats/effect/benchmarks/WorkStealingBenchmark.scala
  build.sbt
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  tests/jvm/src/main/scala/catseffect/examplesplatform.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :beetle: bug

#3829 Improve MapRef docs
  docs/std/mapref.md
  kernel/shared/src/main/scala/cats/effect/kernel/Ref.scala
  std/shared/src/main/scala/cats/effect/std/MapRef.scala
Labels: :books: docs

#3854 Add catch-all category for unlabeled PRs
  .github/release.yml
Labels: :gear: infrastructure

#3857 Update versions for 3.5.2
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#3858 Merge changes from 3.5.2 into series/3.x
  .github/release.yml
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
  kernel/shared/src/main/scala/cats/effect/kernel/Ref.scala
  std/shared/src/main/scala/cats/effect/std/Hotswap.scala
  std/shared/src/main/scala/cats/effect/std/MapRef.scala
  tests/shared/src/test/scala/cats/effect/std/HotswapSpec.scala
Labels: :robot:

#3861 Updated site for 3.5.2
  website/pages/en/index.js
Labels: :robot:
