Repository typelevel/cats-effect, pull requests merged in 2024-03, with the labels that each got.

#3923 Rewrote `Dispatcher`
  build.sbt
  std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
  tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala
Labels: :mushroom: enhancement, Cirrus JVM

#4031 Fix CI step to post release to Discord
  .github/workflows/ci.yml
  build.sbt
Labels: :gear: infrastructure

#4034 Updated site for 3.5.4
  website/pages/en/index.js
Labels: :books: docs, :robot:

#4032 Update versions for 3.5.4
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :books: docs, :robot:

#4036 Create 8-core Cirrus CI job
  .cirrus.yml
Labels: :gear: infrastructure, Cirrus JVM

#4038 Improve contributor documentation
  CONTRIBUTING.md
  RELEASING.md
Labels: :books: docs
