Repository typelevel/cats-effect, pull requests merged in 2024-05, with the labels that each got.

#4054 Document usage of `-Wnonunit-statement`
  docs/faq.md
  docs/getting-started.md
Labels: :books: docs

#4052 `Dispatcher`: avoid spinning
  build.sbt
  std/shared/src/main/scala/cats/effect/std/Dispatcher.scala
Labels: :art: backstage

#3975 Quick and dirty unsafe queue API
  std/shared/src/main/scala/cats/effect/std/Queue.scala
  std/shared/src/main/scala/cats/effect/std/QueueSink.scala
  std/shared/src/main/scala/cats/effect/std/QueueSource.scala
  std/shared/src/main/scala/cats/effect/std/unsafe/BoundedQueue.scala
  std/shared/src/main/scala/cats/effect/std/unsafe/BoundedQueueSink.scala
  std/shared/src/main/scala/cats/effect/std/unsafe/UnboundedQueue.scala
  std/shared/src/main/scala/cats/effect/std/unsafe/UnboundedQueueSink.scala
  tests/jvm/src/test/scala/cats/effect/std/DeferredJVMSpec.scala
  tests/shared/src/test/scala/cats/effect/std/QueueSpec.scala
Labels: :mushroom: enhancement
