Repository typelevel/cats-effect, pull requests merged in 2024-01, with the labels that each got.

#3928 Skip starvation test (which is breaking CI)
  ioapp-tests/src/test/scala/IOAppSpec.scala
Labels: :gear: infrastructure

#3922 Prevent `Hotswap#get` from acquiring a lock when there is no `Resource` present
  std/shared/src/main/scala/cats/effect/std/Hotswap.scala
  tests/shared/src/test/scala/cats/effect/std/HotswapSpec.scala
Labels: :beetle: bug

#3943 Refactor `CallbackStack` based on new "pack locking" strategy
  build.sbt
  core/js/src/main/scala/cats/effect/CallbackStack.scala
  core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
  core/shared/src/main/scala/cats/effect/IODeferred.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
Labels: :beetle: bug, Cirrus JVM

#3951 Tweak release notes config
  .github/release.yml
Labels: :gear: infrastructure

#3952 Decrease concurrency/replicas in `CallbackStackSpec`
  tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
Labels: :art: backstage

#3954 Document release process
  RELEASING.md
Labels: :art: backstage

#3957 Update versions for 3.5.3
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#3959 Updated site for 3.5.3
  website/pages/en/index.js
Labels: :robot:

#3956 Fix Discord post step in release job
  .github/workflows/ci.yml
  build.sbt
Labels: :gear: infrastructure

#3958 Merge changes from 3.5.3 into series/3.x
  .github/release.yml
  README.md
  RELEASING.md
  build.sbt
  core/js-native/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/js/src/main/scala/cats/effect/CallbackStack.scala
  core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/shared/src/main/scala/cats/effect/IODeferred.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
  std/shared/src/main/scala/cats/effect/std/Hotswap.scala
  tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
  tests/shared/src/test/scala/cats/effect/std/HotswapSpec.scala
Labels: :robot:

#3961 Refine steps about post-release scripts
  RELEASING.md
Labels: :art: backstage

#3969 Attempt to cancel the running test in case of a timeout
  tests/shared/src/test/scala/cats/effect/Runners.scala
Labels: :art: backstage

#3968 Add explanatory comment to Mutex implementation
  std/shared/src/main/scala/cats/effect/std/Mutex.scala
Labels: :art: backstage

#3972 Fix a few Supervisor bugs
  build.sbt
  std/shared/src/main/scala/cats/effect/std/Supervisor.scala
  tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
Labels: :beetle: bug

#3973 Clear the CallbackStack more aggressively
  build.sbt
  core/jvm-native/src/main/scala/cats/effect/CallbackStack.scala
  core/shared/src/main/scala/cats/effect/IODeferred.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  tests/shared/src/test/scala/cats/effect/CallbackStackSpec.scala
Labels: :beetle: bug
