Repository typelevel/cats-effect, pull requests merged in 2024-02, with the labels that each got.

#3983 Try to fix issue #3979
  tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala
Labels: :art: backstage

#3987 `IORuntimeConfig`: reject invalid auto-yield and cancelation check thresholds
  core/shared/src/main/scala/cats/effect/unsafe/IORuntimeConfig.scala
  tests/shared/src/test/scala/cats/effect/unsafe/IORuntimeConfigSpec.scala
Labels: :mushroom: enhancement

#3995 Fix typos in `Async` scaladoc
  kernel/shared/src/main/scala/cats/effect/kernel/Async.scala
Labels: :books: docs

#3999 Use dep instead of lib in FAQ docs
  docs/faq.md
Labels: :books: docs

#4001 Fix issue #3998
  std/shared/src/main/scala/cats/effect/std/Queue.scala
  tests/shared/src/test/scala/cats/effect/std/QueueSpec.scala
Labels: :beetle: bug

#3781 Timer stealing without a concurrent data structure
  .github/workflows/ci.yml
  NOTICE.txt
  build.sbt
  core/jvm/src/main/java/cats/effect/unsafe/TimerSkipListNodeBase.java
  core/jvm/src/main/scala/cats/effect/unsafe/TimerHeap.scala
  core/jvm/src/main/scala/cats/effect/unsafe/TimerSkipList.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  project/plugins.sbt
  stress-tests/src/test/scala/cats/effect/unsafe/SkipListTest1.scala
  stress-tests/src/test/scala/cats/effect/unsafe/SkipListTest2.scala
  stress-tests/src/test/scala/cats/effect/unsafe/SkipListTest3.scala
  stress-tests/src/test/scala/cats/effect/unsafe/SkipListTest4.scala
  stress-tests/src/test/scala/cats/effect/unsafe/SkipListTest5.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
  tests/jvm/src/test/scala/cats/effect/unsafe/SleepersSpec.scala
  tests/jvm/src/test/scala/cats/effect/unsafe/TimerHeapSpec.scala
  tests/jvm/src/test/scala/cats/effect/unsafe/TimerSkipListIOSpec.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :mushroom: enhancement, Cirrus JVM

#4003 Fix issue #4002
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :beetle: bug

#3964 Introduce `WeakList` and use in `FiberMonitor`
  core/jvm-native/src/main/scala/cats/effect/unsafe/FiberMonitor.scala
  core/shared/src/main/scala/cats/effect/unsafe/WeakList.scala
Labels: :beetle: bug
