Repository typelevel/cats-effect, pull requests merged in 2024-12, with the labels that each got.

#4194 chore: update LocalQueue docs/comments
  core/jvm/src/main/scala/cats/effect/unsafe/LocalQueue.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
Labels: :books: docs

#4209 Introduce `PollerMetrics`
  core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
  core/jvm-native/src/main/scala/cats/effect/unsafe/metrics/PollerMetrics.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SleepSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/metrics/WorkStealingPoolMetrics.scala
  core/native/src/main/scala/cats/effect/unsafe/EpollSystem.scala
  core/native/src/main/scala/cats/effect/unsafe/KqueueSystem.scala
  core/native/src/main/scala/cats/effect/unsafe/PollingExecutorScheduler.scala
  core/native/src/main/scala/cats/effect/unsafe/SleepSystem.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :mushroom: enhancement

#4210 "completed" -> "succeeded" in `PollerMetrics`
  core/jvm-native/src/main/scala/cats/effect/unsafe/metrics/PollerMetrics.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
Labels: :art: backstage

#4208 Fix MapRef.fromSeqRefs vulnerability
  std/shared/src/main/scala/cats/effect/std/MapRef.scala
Labels: :beetle: bug

#4211 Improve currently-failing tests
  tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala
  tests/shared/src/test/scala/cats/effect/kernel/AsyncSpec.scala
Labels: :art: backstage

#4214 Fixed off-by-one error in other index selection
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  tests/jvm/src/main/scala/catseffect/examplesplatform.scala
Labels: :beetle: bug, Cirrus JVM

#4217 Fix scaladoc, check in CI going forward
  project/CI.scala
  std/shared/src/main/scala/cats/effect/std/MapRef.scala
Labels: :gear: infrastructure
