Repository typelevel/cats-effect, pull requests merged in 2024-11, with the labels that each got.

#4168 Only remove error callback if we've added it
  core/shared/src/main/scala/cats/effect/IO.scala
Labels: :mushroom: enhancement

#4175 Update versions for 3.5.6
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#4177 Updated site for 3.5.6
  website/pages/en/index.js
Labels: :robot:

#4176 Merge changes from 3.5.6 into series/3.x
  README.md
  core/shared/src/main/scala/cats/effect/IO.scala
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
  docs/typeclasses/spawn.md
  std/shared/src/main/scala/cats/effect/std/Dequeue.scala
  tests/shared/src/test/scala/cats/effect/std/QueueSpec.scala
Labels: :robot:

#4167 Propagate Java thread interruption in `Dispatcher#unsafeRunSync`
  std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala
  tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala
Labels: :mushroom: enhancement

#4059 Make `timeout`/`timeoutTo` always return the outcome of the effect
  core/shared/src/main/scala/cats/effect/IO.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenTemporal.scala
  laws/shared/src/test/scala/cats/effect/laws/GenTemporalSpec.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :mushroom: enhancement

#4128 Implement a safer `Resource.attempt` which releases acquired resource(s) in case of error
  core/jvm/src/main/scala/cats/effect/metrics/JvmCpuStarvationMetrics.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  tests/shared/src/test/scala/cats/effect/ResourceSpec.scala
Labels: :beetle: bug

#4185 Updated site for 3.5.7
  website/pages/en/index.js
Labels: :books: docs, :robot:

#4184 Merge changes from 3.5.7 into series/3.x
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
  std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala
  tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala
Labels: :robot:

#4183 Update versions for 3.5.7
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :books: docs, :robot:
