Repository typelevel/cats-effect, pull requests merged in 2024-08, with the labels that each got.

#4111 fixes and attempts to improve scaladoc for Outcome
  kernel/shared/src/main/scala/cats/effect/kernel/Outcome.scala
Labels: :books: docs

#4118 Fix `cancelable` to `guarantee` cancelation
  kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :beetle: bug

#4116 Relax `access` semantics in `MapRef` implementations
  std/shared/src/main/scala/cats/effect/std/MapRef.scala
  tests/jvm/src/test/scala/cats/effect/std/MapRefJVMSpec.scala
  tests/shared/src/test/scala/cats/effect/std/MapRefSpec.scala
Labels: :mushroom: enhancement

#4123 Refresh microsite workflow
  .github/workflows/microsite.yml
  build.sh
  website/.gitignore
  website/package-lock.json
Labels: :art: backstage

#4117 `register` -> `accessPoller`
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
Labels: :art: backstage

#4121 Make `IO#onError` consistent with `ApplicativeError`
  core/shared/src/main/scala/cats/effect/IO.scala
Labels: :beetle: bug
