Repository typelevel/cats-effect, pull requests merged in 2025-01, with the labels that each got.

#4223 Report non-fatal `Runnable` failures on `MainThread` EC
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  ioapp-tests/src/test/scala/IOAppSpec.scala
  tests/jvm/src/main/scala/catseffect/examplesplatform.scala
Labels: :beetle: bug

#4224 Delete .envrc
  .envrc
Labels: :art: backstage

#4226 Add helpers to `Selector` poller
  core/jvm/src/main/scala/cats/effect/Selector.scala
  tests/jvm/src/test/scala/cats/effect/SelectorSpec.scala
Labels: :mushroom: enhancement

#4227 Always report timers/events when worker unparked
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :beetle: bug

#4230 Introduce `PollResult`, `PollingSystem#processReadyEvents`
  core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SleepSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/native/src/main/scala/cats/effect/unsafe/EpollSystem.scala
  core/native/src/main/scala/cats/effect/unsafe/EventLoopExecutorScheduler.scala
  core/native/src/main/scala/cats/effect/unsafe/KqueueSystem.scala
  core/native/src/main/scala/cats/effect/unsafe/PollingExecutorScheduler.scala
  core/native/src/main/scala/cats/effect/unsafe/SleepSystem.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :beetle: bug, ‼️ binary breaking ‼️

#4234 Shutdown the runtime only when unforked
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  tests/jvm/src/main/scala/catseffect/examplesplatform.scala
Labels: :beetle: bug

#4253 Switch to GHA Linux ARM runners
  .cirrus.yml
  .github/workflows/ci.yml
  build.sbt
Labels: :art: backstage

#4257 Fix small typo in docs
  docs/thread-model.md
Labels: :books: docs

#4246 Revert documentation format changes
  .git-blame-ignore-revs
  core/js/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/IOPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/FiberMonitor.scala
  core/jvm/src/main/scala/cats/effect/unsafe/TimerHeap.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/native/src/main/scala/cats/effect/IOApp.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/ResourceApp.scala
  core/shared/src/main/scala/cats/effect/SyncIO.scala
  core/shared/src/main/scala/cats/effect/unsafe/IORuntimeBuilder.scala
  kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala
  kernel/shared/src/main/scala/cats/effect/kernel/MonadCancel.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Ref.scala
  kernel/shared/src/main/scala/cats/effect/kernel/Resource.scala
  testkit/shared/src/main/scala/cats/effect/testkit/TestControl.scala
Labels: :art: backstage

#4259 Add message to requirements
  kernel-testkit/shared/src/main/scala/cats/effect/kernel/testkit/TestContext.scala
  std/shared/src/main/scala/cats/effect/std/Backpressure.scala
  std/shared/src/main/scala/cats/effect/std/Queue.scala
Labels: :mushroom: enhancement
