Repository typelevel/cats-effect, pull requests merged in 2025-04, with the labels that each got.

#4343 Make deprecated `IO.onError` package private
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/shared/src/test/scala-2.13+/not/cats/effect/IOCompilationSpec.scala
Labels: :beetle: bug

#4363 Update versions for 3.6.1
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#4365 PollerMetrics: override toString
  core/jvm-native/src/main/scala/cats/effect/unsafe/metrics/PollerMetrics.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
  tests/jvm/src/test/scala/cats/effect/SelectorSpec.scala
Labels: :mushroom: enhancement

#4364 Merge changes from 3.6.1 into series/3.x
  README.md
  core/jvm-native/src/main/scala/cats/effect/unsafe/PollingSystem.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
  tests/shared/src/test/scala-2.13+/not/cats/effect/IOCompilationSuite.scala
Labels: :robot:

#4372 Updated site for 3.6.1
  website/pages/en/index.js
Labels: :books: docs, :robot:

#4352 Make `IO#syncStep` interpreter stack-safe
  core/shared/src/main/scala/cats/effect/IO.scala
  tests/shared/src/test/scala/cats/effect/IOSpec.scala
Labels: :beetle: bug

#4373 Fix sbt scalafmt check
  project/CI.scala
Labels: :gear: infrastructure

#4375 Set `mayInterruptIfRunning = true` when canceling `CompletableFuture`
  kernel/jvm/src/main/scala/cats/effect/kernel/AsyncPlatform.scala
Labels: :beetle: bug

#4391 Fixed the sample code inconsistency in `IOLocal` scaladoc
  core/shared/src/main/scala/cats/effect/IOLocal.scala
Labels: :books: docs
