Repository typelevel/cats-effect, pull requests merged in 2025-03, with the labels that each got.

#4295 Use `LinkedTransferQueue` for handling cached threads
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
Labels: :mushroom: enhancement, Cirrus JVM

#4290 Don't expose private WSTP type in method signature
  core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala
Labels: :beetle: bug

#4302 Fix betweenDouble/betweenFloat
  std/shared/src/main/scala/cats/effect/std/Random.scala
  tests/shared/src/test/scala/cats/effect/std/RandomSpec.scala
Labels: :beetle: bug

#4311 Update versions for 3.6.0
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#4312 Merge changes from 3.6.0 into series/3.x
  README.md
  core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
  std/shared/src/main/scala/cats/effect/std/Random.scala
  tests/shared/src/test/scala/cats/effect/std/RandomSuite.scala
Labels: :robot:

#4324 Feature: `SecureRandom` instance to `SyncIO` companion
  core/shared/src/main/scala/cats/effect/SyncIO.scala
Labels: :mushroom: enhancement

#4316 Add `realTimeZonedDateTime` to `Clock` JVM extensions
  core/jvm/src/main/scala/cats/effect/IOCompanionPlatform.scala
  kernel/jvm-native/src/main/scala/cats/effect/kernel/ClockPlatform.scala
Labels: :mushroom: enhancement
