Repository typelevel/cats-effect, pull requests merged in 2025-07, with the labels that each got.

#4432 Updated build infrastructure to support Maven Central publication
  build.sbt
  project/CI.scala
  project/build.properties
  project/plugins.sbt
Labels: :art: backstage

#4435 Update versions for 3.6.2
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#4443 Make the heap in `TimerHeap` volatile on native
  core/jvm-native/src/main/scala/cats/effect/unsafe/TimerHeap.scala
Labels: :beetle: bug

#4423 Add `awaitEvent` to expose the full featureset of kqueue
  core/native/src/main/scala/cats/effect/unsafe/KqueueSystem.scala
Labels: :mushroom: enhancement

#4452 Update versions for 3.6.3
  README.md
  docs/core/native-image.md
  docs/core/scala-native.md
  docs/core/test-runtime.md
  docs/faq.md
  docs/getting-started.md
  docs/migration-guide.md
  docs/std/mapref.md
  docs/std/ref.md
  docs/tutorial.md
Labels: :robot:

#4267 Add NonEmptyHotswap
  docs/std/hotswap.md
  std/shared/src/main/scala/cats/effect/std/Hotswap.scala
  std/shared/src/main/scala/cats/effect/std/NonEmptyHotswap.scala
  tests/shared/src/test/scala/cats/effect/std/HotswapSuite.scala
  tests/shared/src/test/scala/cats/effect/std/NonEmptyHotswapSuite.scala
Labels: :mushroom: enhancement

#4362 SN 0.5.6 -> 0.5.7 -> 0.5.8
  build.sbt
  core/native/src/main/scala/cats/effect/unsafe/EpollSystem.scala
  ioapp-tests/src/test/scala/IOAppSuite.scala
  project/plugins.sbt
Labels: Cirrus JVM, Cirrus Native
