Repository typelevel/cats-effect, pull requests merged in 2025-02, with the labels that each got.

#4247 Refactor `WorkerThread` runloop; avoid pathological starvation of pollers
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :beetle: bug, Cirrus JVM

#4264 Transfer tick state when replacing a blocked thread
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :beetle: bug, Cirrus JVM

#4271 `WorkStealingPoolMetrics` -> `WorkStealingThreadPoolMetrics`
  core/jvm/src/main/scala/cats/effect/unsafe/metrics/IORuntimeMetricsCompanionPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/metrics/IORuntimeMetricsPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/metrics/WorkStealingThreadPoolMetrics.scala
Labels: :beetle: bug

#4277 Document `Poll`
  kernel/shared/src/main/scala/cats/effect/kernel/Poll.scala
Labels: :books: docs

#4270 Poll on the 0th tick, check external queue on 32nd
  core/jvm/src/main/java/cats/effect/unsafe/WorkStealingThreadPoolConstants.java
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
Labels: :mushroom: enhancement

#4279 Run finalizers in `IO#unsafeRunTimed`
  core/jvm/src/main/scala/cats/effect/IOPlatform.scala
  tests/jvm/src/test/scala/cats/effect/IOPlatformSpecification.scala
Labels: :beetle: bug

#4263 Create `UnsafeNonFatal` for use in the fiber runtime
  core/js/src/main/scala/cats/effect/unsafe/BatchingMacrotaskExecutor.scala
  core/jvm/src/main/scala/cats/effect/IOApp.scala
  core/jvm/src/main/scala/cats/effect/IOFiberPlatform.scala
  core/jvm/src/main/scala/cats/effect/unsafe/SelectorSystem.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala
  core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala
  core/native/src/main/scala/cats/effect/unsafe/EventLoopExecutorScheduler.scala
  core/shared/src/main/scala/cats/effect/IO.scala
  core/shared/src/main/scala/cats/effect/IOFiber.scala
  core/shared/src/main/scala/cats/effect/SyncIO.scala
  core/shared/src/main/scala/cats/effect/unsafe/UnsafeNonFatal.scala
Labels: :beetle: bug
